/* =========================================================
   IWinit — Offer data source
   Add a new offer by adding one object to OFFERS below.
   Every page (home, category pages, offer detail) reads
   from this single array — no HTML edits required.
   ========================================================= */

const OFFERS = [
  {
    id: "attapoll",
    title: "AttaPoll",
    category: "earn-money",
    categoryLabel: "Survey Apps",
    short: "Answer quick surveys from your phone and get paid out instantly via PayPal.",
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=800&q=60",
    rating: 4.6,
    badges: ["featured", "hot"],
    dateAdded: "2026-06-20",
    tags: ["Worldwide", "PayPal", "Instant Cashout"],
    affiliateUrl: "#",
    earnPotential: "R50–R400 / month",
    countries: "UK, US, South Africa, Australia, Canada, Ireland",
    payment: "PayPal",
    whatIsIt: "AttaPoll is a mobile survey app that pays users in real cash for sharing their opinions on everyday products, services and brands. Surveys typically take two to twenty minutes and rewards land in your balance immediately after each completed survey.",
    howItWorks: "Download the app, build a short profile so surveys are matched to you, then work through the available surveys in your queue. Each one shows the reward and estimated time upfront, so you can choose which to complete.",
    pros: ["Instant payouts with no minimum waiting period", "Clear time and reward estimates before you start", "Light, mobile-first app that works in spare moments"],
    cons: ["Survey availability depends on your demographic profile", "Not a replacement for a full income stream"],
    tips: [
      "Complete your profile fully — it directly increases how many surveys you're matched with.",
      "Check the app in the morning and evening when new surveys are typically released.",
      "Be honest in screening questions; getting screened out repeatedly can reduce future matches."
    ],
    faqs: [
      { q: "Is AttaPoll free to join?", a: "Yes, joining and using AttaPoll costs nothing — you only ever earn." },
      { q: "How fast can I withdraw?", a: "Most users report PayPal withdrawals landing within a day of requesting a cashout." },
      { q: "Do I need a particular country to join?", a: "AttaPoll is open in several countries; availability of individual surveys does vary by region." }
    ]
  },
  {
    id: "swagbucks",
    title: "Swagbucks",
    category: "earn-money",
    categoryLabel: "Cashback & Rewards",
    short: "Earn points for searching, shopping and watching videos, then redeem for cash or gift cards.",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=800&q=60",
    rating: 4.3,
    badges: ["hot"],
    dateAdded: "2026-06-18",
    tags: ["Worldwide", "Gift Cards", "Cashback"],
    affiliateUrl: "#",
    earnPotential: "R100–R600 / month",
    countries: "US, UK, Canada, Australia, South Africa (limited)",
    payment: "PayPal, Gift Cards",
    whatIsIt: "Swagbucks is an all-in-one rewards platform combining cashback shopping, paid surveys, search rewards and offer walls into a single points system called SB, redeemable for cash or gift cards.",
    howItWorks: "Sign up, install the browser extension for automatic cashback tracking, and earn SB points through everyday actions like searching the web, shopping through partner links, or watching short video playlists.",
    pros: ["Many ways to earn beyond surveys alone", "Well-established platform with a long payout track record", "Browser extension automates cashback tracking"],
    cons: ["Point values can feel small for time-heavy tasks", "Best offers often favour US-based members"],
    tips: ["Stack cashback with a manufacturer coupon for compounding savings.", "Set the Swagbucks search engine as default for passive point accrual.", "Watch for seasonal bonus SB promotions around big shopping events."],
    faqs: [
      { q: "What can I redeem SB for?", a: "PayPal cash, dozens of retailer gift cards, and occasional merchandise." },
      { q: "Is there a sign-up bonus?", a: "Swagbucks frequently runs welcome bonuses for new members who complete an initial activity." }
    ]
  },
  {
    id: "amazon-deals",
    title: "Amazon Discount Codes",
    category: "discount-codes",
    categoryLabel: "Amazon",
    short: "Verified promo codes and live deals across electronics, home and fashion on Amazon.",
    image: "https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?auto=format&fit=crop&w=800&q=60",
    rating: 4.7,
    badges: ["featured"],
    dateAdded: "2026-06-25",
    tags: ["Worldwide", "Daily Updated"],
    affiliateUrl: "#",
    earnPotential: "Up to 60% off selected items",
    countries: "Worldwide (region-specific Amazon storefronts)",
    payment: "N/A — discount codes",
    whatIsIt: "A running list of verified Amazon promo codes and lightning deals, checked daily so you only see codes that actually work at checkout.",
    howItWorks: "Browse the current codes, copy the one you want, and apply it at the Amazon checkout page before placing your order. Codes are time-limited, so newest is usually best.",
    pros: ["Codes are checked and refreshed daily", "Covers multiple categories in one place", "No account or sign-up required to browse"],
    cons: ["Some codes are region-locked", "Best discounts sell out quickly on high-demand items"],
    tips: ["Stack a promo code with Amazon's own lightning deals where allowed.", "Add items to your cart before a deal goes live so checkout is instant.", "Check back daily — codes rotate frequently."],
    faqs: [
      { q: "Do I need an account to use these codes?", a: "You just need a regular Amazon account at checkout — no separate sign-up for the codes themselves." },
      { q: "Why did my code fail?", a: "Codes can expire or be region-specific; try the next listed code or check back later in the day." }
    ]
  },
  {
    id: "temu-codes",
    title: "Temu Discount Codes",
    category: "discount-codes",
    categoryLabel: "Temu",
    short: "Fresh percentage-off and free-shipping codes for new and returning Temu shoppers.",
    image: "https://images.unsplash.com/photo-1607082349566-187342175e2f?auto=format&fit=crop&w=800&q=60",
    rating: 4.2,
    badges: ["new"],
    dateAdded: "2026-06-27",
    tags: ["Worldwide", "Free Shipping"],
    affiliateUrl: "#",
    earnPotential: "Up to 90% off + free shipping",
    countries: "Worldwide",
    payment: "N/A — discount codes",
    whatIsIt: "A curated list of Temu coupon codes covering new-customer discounts, spin-the-wheel bonuses and free shipping thresholds.",
    howItWorks: "Open the Temu app or site, add items to your cart, then enter the code at checkout in the promo code field before paying.",
    pros: ["New-customer codes can be very high value", "Free shipping codes stack with item discounts", "Updated as Temu rotates its promotions"],
    cons: ["Best codes are usually first-order only", "Delivery times vary by region"],
    tips: ["First-time codes give the deepest discount — use your biggest cart for that order.", "Check the in-app daily check-in for extra coupon drops."],
    faqs: [{ q: "Can I use more than one code per order?", a: "Temu typically allows one promo code per order alongside any automatic platform discounts." }]
  },
  {
    id: "free-ebooks",
    title: "Free eBooks Library",
    category: "freebies",
    categoryLabel: "Free eBooks",
    short: "A rotating list of legally free eBooks across business, fiction and self-improvement.",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=800&q=60",
    rating: 4.5,
    badges: ["new"],
    dateAdded: "2026-06-22",
    tags: ["Worldwide", "No Sign-up"],
    affiliateUrl: "#",
    earnPotential: "100% free",
    countries: "Worldwide",
    payment: "N/A — free",
    whatIsIt: "A regularly refreshed list of free, legitimately licensed eBooks — including limited-time free promotions from publishers and permanently free public-domain classics.",
    howItWorks: "Browse the list, click through to the official source (publisher site or library platform), and download in your preferred format.",
    pros: ["Always legal, licensed sources only", "Mix of fresh promotions and timeless classics", "No account required for public-domain titles"],
    cons: ["Promotional free books are time-limited", "Selection depends on what publishers offer that week"],
    tips: ["Limited-time promo eBooks often expire within 48 hours — grab them early.", "Public-domain classics are free forever, so there's no rush on those."],
    faqs: [{ q: "Are these books really free, no trial?", a: "Yes — every title listed is either public domain or a genuine time-limited publisher promotion, never a disguised trial." }]
  },
  {
    id: "canva-pro-trial",
    title: "Canva Pro Free Trial",
    category: "freebies",
    categoryLabel: "Free Software",
    short: "Get full access to Canva Pro's premium templates and tools free for a limited trial period.",
    image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=800&q=60",
    rating: 4.8,
    badges: ["featured", "hot"],
    dateAdded: "2026-06-28",
    tags: ["Worldwide", "No Card Sometimes"],
    affiliateUrl: "#",
    earnPotential: "30-day free access",
    countries: "Worldwide",
    payment: "N/A — free trial",
    whatIsIt: "Canva Pro unlocks premium templates, the background remover, brand kits and resizing tools on top of the free Canva editor — available through a free trial period.",
    howItWorks: "Sign up for a Canva account, activate the Pro trial from your account settings, and use the full toolset until the trial period ends.",
    pros: ["Full premium toolset, not a watered-down version", "Great for testing brand kits before committing", "Cancel any time before the trial ends to avoid charges"],
    cons: ["Requires payment details on some sign-up paths", "Reverts to free tier features after the trial unless you subscribe"],
    tips: ["Set a calendar reminder two days before trial end so you're never charged unexpectedly.", "Batch your design work during the trial to get full value from premium templates."],
    faqs: [{ q: "Will I be charged automatically?", a: "If the trial requires card details, it converts to a paid plan unless cancelled before the trial ends — always check your account settings." }]
  },
  {
    id: "freelance-writing",
    title: "Freelance Writing Gigs",
    category: "earn-money",
    categoryLabel: "Freelancing",
    short: "A curated feed of beginner-friendly freelance writing gigs from vetted client boards.",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=60",
    rating: 4.4,
    badges: [],
    dateAdded: "2026-06-15",
    tags: ["Remote", "Beginner Friendly"],
    affiliateUrl: "#",
    earnPotential: "R500–R8,000+ / month",
    countries: "Remote, worldwide",
    payment: "Bank Transfer, PayPal, Payoneer",
    whatIsIt: "A directory pointing to active freelance writing opportunities, from one-off blog posts to ongoing content contracts, filtered for legitimacy and beginner accessibility.",
    howItWorks: "Browse the listed boards, build a short portfolio of two to three sample pieces, then pitch directly using the contact details on each listing.",
    pros: ["Genuinely beginner-accessible listings", "No middleman fee taken from your earnings", "Wide range of niches to specialise in"],
    cons: ["Requires consistent pitching effort to land first clients", "Income is variable, especially in the first months"],
    tips: ["Lead your pitch with a relevant writing sample, not a generic introduction.", "Specialise in one or two niches to build a recognisable portfolio faster."],
    faqs: [{ q: "Do I need a degree to start freelance writing?", a: "No — most clients care about clear, relevant writing samples far more than formal qualifications." }]
  },
  {
    id: "win-iphone",
    title: "Win an iPhone 17 Pro",
    category: "competitions",
    categoryLabel: "Win Phones",
    short: "Free monthly giveaway for the latest iPhone — no purchase necessary to enter.",
    image: "https://images.unsplash.com/photo-1592286927505-1def25115558?auto=format&fit=crop&w=800&q=60",
    rating: 4.5,
    badges: ["hot"],
    dateAdded: "2026-06-19",
    tags: ["Worldwide", "Free Entry"],
    affiliateUrl: "#",
    earnPotential: "1 winner / month",
    countries: "Worldwide",
    payment: "N/A — prize giveaway",
    whatIsIt: "A free-to-enter monthly competition giving away the newest flagship iPhone to one verified winner, run transparently with a public draw date.",
    howItWorks: "Enter your details on the competition page, optionally get bonus entries by sharing, and wait for the live draw — winners are notified directly and announced publicly.",
    pros: ["Completely free entry, no purchase required", "Transparent draw process with public winner announcement", "Bonus entries available through simple sharing actions"],
    cons: ["Odds depend on total entrants that month", "One winner per draw period"],
    tips: ["Use the bonus-entry sharing option to multiply your chances at no cost.", "Double-check your contact details are correct so you can be reached if you win."],
    faqs: [{ q: "Is this really free to enter?", a: "Yes — entry never requires a purchase. Optional sharing actions simply add bonus entries." }]
  },
  {
    id: "remote-support-jobs",
    title: "Remote Customer Support Roles",
    category: "jobs",
    categoryLabel: "Remote",
    short: "Entry-level remote customer support openings from companies hiring across time zones.",
    image: "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?auto=format&fit=crop&w=800&q=60",
    rating: 4.1,
    badges: ["new"],
    dateAdded: "2026-06-26",
    tags: ["Remote", "Full Time", "Part Time"],
    affiliateUrl: "#",
    earnPotential: "R8,000–R18,000 / month",
    countries: "Remote, region restrictions vary by listing",
    payment: "Salary, paid monthly",
    whatIsIt: "A filtered feed of legitimate remote customer support and live-chat positions, screened to remove pay-to-apply scams.",
    howItWorks: "Browse the open roles, check the region and shift requirements on each listing, then apply directly through the employer's own application link.",
    pros: ["All listings screened against common scam patterns", "Mix of full-time and part-time shift options", "Entry-level roles included, not just experienced hires"],
    cons: ["Some roles restricted to specific time zones", "Competitive roles can fill quickly"],
    tips: ["Tailor your application to the specific tools mentioned in the listing (e.g. Zendesk, Intercom).", "Apply within the first 48 hours of a listing going live for the best response rate."],
    faqs: [{ q: "Are these jobs free to apply to?", a: "Yes — any listing requesting payment to apply is excluded and should be treated as a scam." }]
  },
  {
    id: "student-laptop-deals",
    title: "Student Laptop Discounts",
    category: "student-deals",
    categoryLabel: "Laptops",
    short: "Verified student-pricing programmes from major laptop brands, with proof-of-status guidance.",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=60",
    rating: 4.6,
    badges: ["featured"],
    dateAdded: "2026-06-21",
    tags: ["Students Only", "Worldwide"],
    affiliateUrl: "#",
    earnPotential: "Up to 20% off + free accessories",
    countries: "Worldwide, verification method varies",
    payment: "N/A — discount programme",
    whatIsIt: "A breakdown of official student discount programmes from major laptop manufacturers, including which ID verification service each one uses.",
    howItWorks: "Verify your student status through the listed provider (usually a quick ID-check service), then apply the resulting discount code on the brand's official store.",
    pros: ["Official manufacturer programmes, not resellers", "Often bundled with free accessories or software", "Verification is usually a one-time five-minute process"],
    cons: ["Requires valid proof of current enrolment", "Some configurations excluded from the discount"],
    tips: ["Verify once, then re-use the same discount link for future purchases within the academic year.", "Check for bundled software offers (e.g. Office) stacked onto the hardware discount."],
    faqs: [{ q: "What counts as proof of student status?", a: "Typically a current student email address or enrolment document through the brand's verification partner." }]
  },
  {
    id: "spotify-student",
    title: "Spotify Student Discount",
    category: "student-deals",
    categoryLabel: "Spotify",
    short: "Half-price Spotify Premium bundled with Hulu and SHOWTIME for verified students.",
    image: "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?auto=format&fit=crop&w=800&q=60",
    rating: 4.7,
    badges: [],
    dateAdded: "2026-06-12",
    tags: ["Students Only"],
    affiliateUrl: "#",
    earnPotential: "50% off, up to 4 years",
    countries: "Available where Spotify Premium operates",
    payment: "N/A — subscription discount",
    whatIsIt: "Spotify's official student plan offers Premium at roughly half price, often bundled with additional streaming services, for the duration of your studies.",
    howItWorks: "Verify enrolment through Spotify's partner verification service, then the discounted billing applies automatically to your account.",
    pros: ["Significant ongoing discount, not a one-off", "Bundled extras add meaningful value", "Re-verifies automatically each year while you're enrolled"],
    cons: ["Annual re-verification required", "Discount ends once enrolment can no longer be verified"],
    tips: ["Re-verify as soon as you get the reminder email to avoid a billing gap."],
    faqs: [{ q: "How long does the discount last?", a: "It can be renewed annually for as long as you remain a verified student, up to the programme's stated maximum." }]
  },
  {
    id: "uber-eats-codes",
    title: "Uber Eats Daily Promo",
    category: "daily-deals",
    categoryLabel: "Daily Deals",
    short: "Fresh percentage-off and free-delivery codes for Uber Eats, refreshed every day.",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=60",
    rating: 4.3,
    badges: ["new"],
    dateAdded: "2026-06-30",
    tags: ["Worldwide", "Daily Updated"],
    affiliateUrl: "#",
    earnPotential: "Up to 50% off first orders",
    countries: "Worldwide, where Uber Eats operates",
    payment: "N/A — discount codes",
    whatIsIt: "A daily-refreshed list of Uber Eats promo codes covering percentage discounts, free delivery thresholds and restaurant-specific offers.",
    howItWorks: "Open the app, browse to checkout, and enter the day's code in the promotions field before confirming your order.",
    pros: ["New codes daily, so there's almost always something live", "Mix of platform-wide and restaurant-specific codes", "Easy to apply directly in-app"],
    cons: ["Best codes are often new-customer only", "Minimum order values apply to some codes"],
    tips: ["Check back each morning — the best codes tend to be used up by evening."],
    faqs: [{ q: "Can existing customers use these codes too?", a: "Many of the listed codes are open to all customers, though the highest-value ones are usually first-order exclusives." }]
  },
  {
    id: "nike-sale",
    title: "Nike Outlet Discount Codes",
    category: "discount-codes",
    categoryLabel: "Nike",
    short: "Stacking codes for Nike's outlet section — combine with sale prices for maximum savings.",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=60",
    rating: 4.4,
    badges: [],
    dateAdded: "2026-06-17",
    tags: ["Worldwide"],
    affiliateUrl: "#",
    earnPotential: "Up to 40% off outlet prices",
    countries: "Worldwide, region-specific stores",
    payment: "N/A — discount codes",
    whatIsIt: "Promo codes specifically valid on Nike's already-discounted outlet section, letting you stack an extra percentage off clearance pricing.",
    howItWorks: "Shop the outlet section first, add items to your cart, then apply the listed code at checkout to stack the additional discount.",
    pros: ["Stacks on top of existing outlet markdowns", "Covers footwear and apparel categories", "Refreshed as Nike rotates outlet promotions"],
    cons: ["Outlet sizes and colours sell out fast", "Codes occasionally exclude select collaborations"],
    tips: ["Sort the outlet section by 'newest' to catch fresh markdowns before stock runs low."],
    faqs: [{ q: "Do these codes work on full-price items?", a: "These specific codes are intended for the outlet section; full-price eligibility varies by current promotion." }]
  },
  {
    id: "fiverr-freelance",
    title: "Fiverr Freelance Marketplace",
    category: "earn-money",
    categoryLabel: "Freelancing",
    short: "Turn a skill into income by listing gigs on one of the largest freelance marketplaces.",
    image: "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=60",
    rating: 4.2,
    badges: [],
    dateAdded: "2026-06-10",
    tags: ["Remote", "Worldwide"],
    affiliateUrl: "#",
    earnPotential: "R200–R10,000+ / month",
    countries: "Worldwide",
    payment: "PayPal, Bank Transfer",
    whatIsIt: "Fiverr is a global freelance marketplace where you create 'gigs' describing a service you offer, and buyers come directly to you.",
    howItWorks: "Set up a seller profile, create a clearly priced gig with examples of your work, and respond promptly to buyer requests to build reviews.",
    pros: ["No cold-pitching required — buyers come to you", "Built-in payment protection", "Easy to test multiple gig ideas at once"],
    cons: ["Platform fee taken from each sale", "New sellers need time to build review history"],
    tips: ["Your gig thumbnail and title matter more than almost anything else for getting clicks.", "Respond to buyer messages quickly — response time affects how often you're shown."],
    faqs: [{ q: "How much commission does Fiverr take?", a: "Fiverr takes a percentage service fee from each completed order, which is deducted before payout." }]
  },
  {
    id: "win-cash-giveaway",
    title: "R10,000 Cash Giveaway",
    category: "competitions",
    categoryLabel: "Win Cash",
    short: "Quarterly cash giveaway open to all entrants — verified, transparent draw with no purchase needed.",
    image: "https://images.unsplash.com/photo-1554672408-730436b60986?auto=format&fit=crop&w=800&q=60",
    rating: 4.0,
    badges: ["featured"],
    dateAdded: "2026-06-14",
    tags: ["Free Entry", "Worldwide"],
    affiliateUrl: "#",
    earnPotential: "1 winner / quarter",
    countries: "Worldwide",
    payment: "N/A — prize giveaway",
    whatIsIt: "A quarterly cash giveaway with a transparent, verifiable draw process and a single confirmed winner announced publicly each cycle.",
    howItWorks: "Submit your entry on the competition page before the closing date, then watch the public draw announcement to see if you've won.",
    pros: ["No purchase required to enter", "Transparent, publicly verifiable draw", "Decent prize pool for a single quarterly winner"],
    cons: ["Lower odds given open worldwide entry", "Only one winner selected per quarter"],
    tips: ["Mark the draw date in your calendar so you don't miss the winner announcement."],
    faqs: [{ q: "Is identity verification required to claim the prize?", a: "Winners are typically asked for basic identity verification before the prize is paid out, which is standard for legitimate giveaways." }]
  }
];

/* Category metadata used across pages */
const CATEGORIES = [
  { slug: "daily-deals", label: "Daily Deals", emoji: "🔥" },
  { slug: "earn-money", label: "Earn Money", emoji: "💰" },
  { slug: "freebies", label: "Freebies", emoji: "🎁" },
  { slug: "student-deals", label: "Student Deals", emoji: "🎓" },
  { slug: "jobs", label: "Jobs", emoji: "💼" },
  { slug: "competitions", label: "Competitions", emoji: "🏆" },
  { slug: "discount-codes", label: "Discount Codes", emoji: "🏷️" },
];

if (typeof module !== "undefined") { module.exports = { OFFERS, CATEGORIES }; }
